- name: Generate Tiller certificate
  command: ./tls/generate_cert.sh tiller server tiller-server
  args:
    creates: tls/tiller/tiller-server.pem

- name: Generate Helm client certificate
  command: ./tls/generate_cert.sh tiller client helm-client
  args:
    creates: tls/tiller/helm-client.pem

- name: Generate Helm user SSH key pair
  command: ssh-keygen -t rsa -f tls/tiller/id_rsa_helm -N ""
  args:
    creates: tls/tiller/id_rsa_helm

- name: Clear Tiller configuration directory
  file:
    dest: ./tiller_config
    state: absent
- name: Prepare Tiller configuration directory
  file:
    dest: ./tiller_config
    state: directory

- name: Initialize templated configuration files
  template:
    src: "{{ item }}"
    dest: "./tiller_config/{{ item | basename | regex_replace('\\.j2$','') }}"
  with_fileglob:
  - '../templates/*.yaml.j2'

- name: Create Tiller certificates secret
  command: kubectl apply -f ./tiller_config/certs.yaml
- name: Create Tiller deployment
  command: kubectl apply -f ./tiller_config/deployment.yaml
- name: Create Tiller service
  command: kubectl apply -f ./tiller_config/svc.yaml

# SSH+Helm cluster internal service

- name: Create Helm client certificates secret
  command: kubectl apply -f ./tiller_config/helm-certs.yaml

- name: Create SSH+Helm deployment
  command: kubectl apply -f ./tiller_config/helm-deployment.yaml

- name: Create Helm SSH service
  command: kubectl apply -f ./tiller_config/helm-svc.yaml
