apiVersion: v1
kind: Namespace
metadata:
  name: nmaas
  labels:
    name: nmaas

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nmaas-admin
  namespace: nmaas

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nmaas-admin
subjects:
  - kind: ServiceAccount
    name: nmaas-admin
    namespace: nmaas
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

