apiVersion: v1
kind: Namespace
metadata:
  name: nmaas
  labels:
    name: nmaas

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nmaas-admin
  namespace: nmaas

---

kind: PodSecurityPolicy
apiVersion: extensions/v1beta1
metadata:
  annotations:
  name: restricted-chroot
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - KILL
  - CHOWN
  - FSETID
  - FOWNER
  - NET_RAW
  - SETGID
  - SETUID
  - SETFCAP
  - SETPCAP
  - SYS_CHROOT
  - DAC_OVERRIDE
  - AUDIT_WRITE
  - NET_BIND_SERVICE
  - DAC_READ_SEARCH
  fsGroup:
    rule: RunAsAny
  requiredDropCapabilities:
  - MKNOD
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - emptyDir
  - secret
  - downwardAPI
  - configMap
  - persistentVolumeClaim
  - projected

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restricted-chroot-psp
rules:
- apiGroups:
  - extensions
  resourceNames:
  - restricted-chroot
  resources:
  - podsecuritypolicies
  verbs:
  - use

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nmaas-admin
subjects:
  - kind: ServiceAccount
    name: nmaas-admin
    namespace: nmaas
roleRef:
  kind: ClusterRole
  name: restricted-chroot-psp
  apiGroup: rbac.authorization.k8s.io

